# Generated by Django 5.1.6 on 2025-03-05 00:24

import django.db.migrations.operations.special
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('ips4', '0001_initial'), ('ips4', '0002_service_permissions')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ips4User',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='ips4', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('username', models.CharField(max_length=254)),
                ('id', models.CharField(max_length=254)),
            ],
            options={
                'default_permissions': (),
                'permissions': (('access_ips4', 'Can access the IPS4 service'),),
            },
        ),
    ]
