# Generated by Django 6.0.5 on 2026-05-13 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlueprintCopyListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_label', models.CharField(help_text='Display only; link to AA user in a later migration.', max_length=128)),
                ('type_id', models.PositiveIntegerField()),
                ('runs_remaining', models.PositiveIntegerField(blank=True, null=True)),
                ('material_efficiency', models.PositiveSmallIntegerField(default=0)),
                ('time_efficiency', models.PositiveSmallIntegerField(default=0)),
                ('is_available', models.BooleanField(default=True)),
                ('location_note', models.CharField(blank=True, max_length=256)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('type_id', 'id'),
            },
        ),
        migrations.CreateModel(
            name='IndustrialProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('esi_corporation_id', models.BigIntegerField()),
                ('esi_external_ref', models.CharField(blank=True, help_text='Opaque id from ESI (e.g. corporation project id) when available.', max_length=128)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='IndustrialSubOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=256)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('type_id', models.PositiveIntegerField(blank=True, help_text='SDE type id when known.', null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('claimed', 'Claimed'), ('in_progress', 'In progress'), ('done_esi', 'Verified complete (ESI)'), ('cancelled', 'Cancelled')], default='open', max_length=32)),
                ('claimed_by_discord_id', models.BigIntegerField(blank=True, null=True)),
                ('claimed_by_character_id', models.PositiveIntegerField(blank=True, null=True)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_orders', to='industry_suite.industrialproject')),
            ],
            options={
                'ordering': ('project_id', 'id'),
            },
        ),
    ]
