# Generated by Django 6.0.5 on 2026-05-13 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('industry_suite', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='industrialsuborder',
            options={'ordering': ('project', 'id')},
        ),
    ]
