# Generated by Django 5.2.12 on 2026-03-12 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fleetactivitytracking", "0008_v5squash"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="fat",
            options={"default_permissions": ()},
        ),
    ]
