# Generated by Django 5.2.12 on 2026-03-12 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_css", "0002_customcss_css_compressed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customcss",
            name="css",
            field=models.TextField(
                blank=True,
                default="",
                help_text="This CSS will be added to the site after the default CSS.",
                verbose_name="Your custom CSS",
            ),
        ),
    ]
