# Generated by Django 5.1.6 on 2025-03-05 00:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('discord', '0001_initial'), ('discord', '0002_service_permissions'), ('discord', '0003_big_overhaul')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordUser',
            fields=[
                ('user', models.OneToOneField(help_text='Auth user owning this Discord account', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='discord', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('uid', models.BigIntegerField(db_index=True, help_text="user's ID on Discord")),
                ('activated', models.DateTimeField(blank=True, default=None, help_text='Date & time this service account was activated', null=True)),
                ('discriminator', models.CharField(blank=True, default='', help_text="user's discriminator on Discord", max_length=4)),
                ('username', models.CharField(blank=True, db_index=True, default='', help_text="user's username on Discord", max_length=32)),
            ],
            options={
                'default_permissions': (),
                'permissions': (('access_discord', 'Can access the Discord service'),),
            },
        ),
    ]
