# Generated by Django 5.1.6 on 2025-03-04 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eveonline', '0017_alliance_and_corp_names_are_not_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evecharacter',
            name='alliance_name',
            field=models.CharField(blank=True, default='', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='evecharacter',
            name='alliance_ticker',
            field=models.CharField(blank=True, default='', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='evecharacter',
            name='faction_name',
            field=models.CharField(blank=True, default='', max_length=254, null=True),
        ),
    ]
