# Generated by Django 5.2.12 on 2026-03-12 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eveonline", "0019_v5squash"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="eveallianceinfo",
            options={"default_permissions": ()},
        ),
        migrations.AlterModelOptions(
            name="evefactioninfo",
            options={"default_permissions": ()},
        ),
        migrations.RemoveIndex(
            model_name="eveallianceinfo",
            name="eveonline_e_executo_7f3280_idx",
        ),
        migrations.AlterField(
            model_name="eveallianceinfo",
            name="executor_corp_id",
            field=models.PositiveIntegerField(db_index=True),
        ),
    ]
