# Generated by Django 5.2.12 on 2026-03-31 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eveonline", "0020_alter_eveallianceinfo_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="eveallianceinfo",
            options={
                "default_permissions": (),
                "verbose_name": "alliance",
                "verbose_name_plural": "alliances",
            },
        ),
        migrations.AlterModelOptions(
            name="evecharacter",
            options={"verbose_name": "character", "verbose_name_plural": "characters"},
        ),
        migrations.AlterModelOptions(
            name="evecorporationinfo",
            options={
                "verbose_name": "corporation",
                "verbose_name_plural": "corporations",
            },
        ),
        migrations.AlterModelOptions(
            name="evefactioninfo",
            options={
                "default_permissions": (),
                "verbose_name": "faction",
                "verbose_name_plural": "factions",
            },
        ),
        migrations.AddField(
            model_name="eveallianceinfo",
            name="last_updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="evecharacter",
            name="last_updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="evecorporationinfo",
            name="last_updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="evefactioninfo",
            name="last_updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
