# Generated by Django 5.1.6 on 2025-03-05 00:23

import django.db.migrations.operations.special
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('discourse', '0001_initial'), ('discourse', '0002_service_permissions')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscourseUser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='discourse', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('enabled', models.BooleanField()),
            ],
            options={
                'default_permissions': (),
                'permissions': (('access_discourse', 'Can access the Discourse service'),),
            },
        ),
    ]
