# Generated by Django 5.2.12 on 2026-03-12 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("corputils", "0006_v5squash"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="corpmember",
            options={
                "default_permissions": (),
                "ordering": ["character_name"],
                "verbose_name": "Corp Member",
                "verbose_name_plural": "Corp Members",
            },
        ),
        migrations.AlterModelOptions(
            name="corpstats",
            options={
                "default_permissions": (),
                "permissions": (
                    (
                        "view_corp_corpstats",
                        "Can view corp stats of their corporation.",
                    ),
                    (
                        "view_alliance_corpstats",
                        "Can view corp stats of members of their alliance.",
                    ),
                    (
                        "view_state_corpstats",
                        "Can view corp stats of members of their auth state.",
                    ),
                ),
                "verbose_name": "Corp Stat",
                "verbose_name_plural": "Corp Stats",
            },
        ),
    ]
