# Generated by Django 5.2.12 on 2026-04-29 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corputils', '0007_alter_corpmember_options_alter_corpstats_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='corpstats',
            options={'default_permissions': ('add',), 'permissions': (('view_corp_corpstats', 'Can view corp stats of their corporation.'), ('view_alliance_corpstats', 'Can view corp stats of members of their alliance.'), ('view_state_corpstats', 'Can view corp stats of members of their auth state.')), 'verbose_name': 'Corp Stat', 'verbose_name_plural': 'Corp Stats'},
        ),
    ]
