# Generated by Django 5.1.6 on 2025-03-04 01:03

# This was built by Deleting Every Migration, Creating one from scratch
# And porting in anything necessary

import uuid

from django.db import migrations, models


def add_aa_team_token(apps, schema_editor):
    Tokens = apps.get_model('analytics', 'AnalyticsTokens')
    token = Tokens()

    token.type = 'GA-V4'
    token.token = 'G-6LYSMYK8DE'
    token.secret = 'KLlpjLZ-SRGozS5f5wb_kw'
    token.name = 'AA Team Public Google Analytics (V4)'
    token.save()


class Migration(migrations.Migration):

    replaces = [('analytics', '0001_initial'), ('analytics', '0002_add_AA_Team_Token'), ('analytics', '0003_Generate_Identifier'), ('analytics', '0004_auto_20211015_0502'), ('analytics', '0005_alter_analyticspath_ignore_path'), ('analytics', '0006_more_ignore_paths'), ('analytics', '0007_analyticstokens_secret'), ('analytics', '0008_add_AA_GA-4_Team_Token '), ('analytics', '0009_remove_analyticstokens_ignore_paths_and_more'), ('analytics', '0010_alter_analyticsidentifier_options')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsIdentifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
            options={
                'verbose_name': 'Analytics Identifier',
            },
        ),
        migrations.CreateModel(
            name='AnalyticsTokens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('type', models.CharField(choices=[('GA-U', 'Google Analytics Universal'), ('GA-V4', 'Google Analytics V4')], max_length=254)),
                ('token', models.CharField(max_length=254)),
                ('secret', models.CharField(blank=True, max_length=254)),
                ('send_stats', models.BooleanField(default=False)),
            ],
        ),
        migrations.RunPython(
            add_aa_team_token
        ),
    ]
