# Generated by Django 5.2.13 on 2026-04-10 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0011_v5squash"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="analyticsidentifier",
            options={"verbose_name": "analytics identifier"},
        ),
        migrations.AlterModelOptions(
            name="analyticstokens",
            options={
                "verbose_name": "analytics token",
                "verbose_name_plural": "analytics tokens",
            },
        ),
    ]
