# Generated by Django 4.2.28 on 2026-03-02 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eve_sde', '0017_remove_itemtype_market_group_id_raw'),
        ('marketmanager', '0058_alter_marginconfig_destination_buy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managedsupplyconfig',
            name='managed_region',
            field=models.ManyToManyField(blank=True, related_name='+', to='eve_sde.region', verbose_name='Region'),
        ),
        migrations.AlterField(
            model_name='managedsupplyconfig',
            name='managed_solar_system',
            field=models.ManyToManyField(blank=True, to='eve_sde.solarsystem', verbose_name='Solar System'),
        ),
        migrations.AlterField(
            model_name='managedsupplyconfig',
            name='managed_structure_type',
            field=models.ManyToManyField(blank=True, help_text='Filter by structure Type/Size/Docking (ie, forts/keeps for cap fuel)', to='eve_sde.itemtype', verbose_name='Structure Type Filter'),
        ),
        migrations.AlterField(
            model_name='marginconfig',
            name='destination_region',
            field=models.ManyToManyField(blank=True, related_name='+', to='eve_sde.region', verbose_name='Destination Region'),
        ),
        migrations.AlterField(
            model_name='marginconfig',
            name='destination_solar_system',
            field=models.ManyToManyField(blank=True, related_name='+', to='eve_sde.solarsystem', verbose_name='Destination Solar System'),
        ),
        migrations.AlterField(
            model_name='marginconfig',
            name='destination_station',
            field=models.ManyToManyField(blank=True, related_name='+', to='eve_sde.npcstation', verbose_name='Destination Station'),
        ),
        migrations.AlterField(
            model_name='marginconfig',
            name='eve_group',
            field=models.ManyToManyField(blank=True, related_name='+', to='eve_sde.itemgroup', verbose_name='EVE Inventory Group'),
        ),
        migrations.AlterField(
            model_name='marginconfig',
            name='eve_market_group',
            field=models.ManyToManyField(blank=True, related_name='+', to='eve_sde.itemmarketgroup', verbose_name='EVE Market Group'),
        ),
        migrations.AlterField(
            model_name='marginconfig',
            name='eve_type',
            field=models.ManyToManyField(blank=True, related_name='+', to='eve_sde.itemtype', verbose_name='EVE Type'),
        ),
        migrations.AlterField(
            model_name='marginconfig',
            name='source_region',
            field=models.ManyToManyField(blank=True, related_name='+', to='eve_sde.region', verbose_name='Source Region'),
        ),
        migrations.AlterField(
            model_name='marginconfig',
            name='source_solar_system',
            field=models.ManyToManyField(blank=True, related_name='+', to='eve_sde.solarsystem', verbose_name='Source Solar System'),
        ),
        migrations.AlterField(
            model_name='marginconfig',
            name='source_station',
            field=models.ManyToManyField(blank=True, related_name='+', to='eve_sde.npcstation', verbose_name='Source Station'),
        ),
        migrations.AlterField(
            model_name='order',
            name='eve_region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='eve_sde.region', verbose_name='Region'),
        ),
        migrations.AlterField(
            model_name='order',
            name='eve_solar_system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eve_sde.solarsystem', verbose_name='System'),
        ),
        migrations.AlterField(
            model_name='order',
            name='eve_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eve_sde.itemtype', verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='priceconfig',
            name='eve_group',
            field=models.ManyToManyField(blank=True, to='eve_sde.itemgroup', verbose_name='EVE Inventory Group'),
        ),
        migrations.AlterField(
            model_name='priceconfig',
            name='eve_market_group',
            field=models.ManyToManyField(blank=True, to='eve_sde.itemmarketgroup', verbose_name='EVE Market Group'),
        ),
        migrations.AlterField(
            model_name='priceconfig',
            name='eve_type',
            field=models.ManyToManyField(blank=True, to='eve_sde.itemtype', verbose_name='EVE Type'),
        ),
        migrations.AlterField(
            model_name='priceconfig',
            name='region',
            field=models.ManyToManyField(blank=True, related_name='+', to='eve_sde.region', verbose_name='Region'),
        ),
        migrations.AlterField(
            model_name='priceconfig',
            name='solar_system',
            field=models.ManyToManyField(blank=True, to='eve_sde.solarsystem', verbose_name='Solar System'),
        ),
        migrations.AlterField(
            model_name='priceconfig',
            name='structure_type',
            field=models.ManyToManyField(blank=True, help_text='Filter by structure Type/Size/Docking (ie, forts/keeps for cap fuel)', related_name='+', to='eve_sde.itemtype', verbose_name='Structure Type Filter'),
        ),
        migrations.AlterField(
            model_name='publicconfig',
            name='fetch_regions',
            field=models.ManyToManyField(related_name='+', to='eve_sde.region', verbose_name='Fetch Regions'),
        ),
        migrations.AlterField(
            model_name='statisticsconfig',
            name='calculate_regions',
            field=models.ManyToManyField(to='eve_sde.region', verbose_name='TypeStatistics Calculation Regions'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='eve_type',
            field=models.ForeignKey(limit_choices_to={'eve_group__id__in': [15, 1657], 'published': 1}, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='eve_sde.itemtype', verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='solar_system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='eve_sde.solarsystem', verbose_name='Solar System'),
        ),
        migrations.AlterField(
            model_name='supplyconfig',
            name='eve_type',
            field=models.ForeignKey(limit_choices_to={'eve_market_group__isnull': False, 'published': 1}, on_delete=django.db.models.deletion.CASCADE, to='eve_sde.itemtype', verbose_name='EVE Type'),
        ),
        migrations.AlterField(
            model_name='supplyconfig',
            name='region',
            field=models.ManyToManyField(blank=True, related_name='+', to='eve_sde.region', verbose_name='Region'),
        ),
        migrations.AlterField(
            model_name='supplyconfig',
            name='solar_system',
            field=models.ManyToManyField(blank=True, to='eve_sde.solarsystem', verbose_name='Solar System'),
        ),
        migrations.AlterField(
            model_name='supplyconfig',
            name='structure_type',
            field=models.ManyToManyField(blank=True, help_text='Filter by structure Type/Size/Docking (ie, forts/keeps for cap fuel)', related_name='+', to='eve_sde.itemtype', verbose_name='Structure Type Filter'),
        ),
        migrations.AlterField(
            model_name='typestatistics',
            name='eve_region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='eve_sde.region', verbose_name='Region'),
        ),
        migrations.AlterField(
            model_name='typestatistics',
            name='eve_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eve_sde.itemtype', verbose_name='Type'),
        ),
    ]
