# Generated by Django 4.2.28 on 2026-03-02 12:52

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('marketmanager', '0001_squashed_0014_alter_privateconfig_valid_corporations_and_more'), ('marketmanager', '0002_alter_structure_created_at_alter_watchconfig_type'), ('marketmanager', '0003_rename_type_watchconfig_eve_type'), ('marketmanager', '0004_alter_watchconfig_jita_compare_percent_and_more'), ('marketmanager', '0005_alter_watchconfig_constellation_and_more'), ('marketmanager', '0006_watchconfig_config_type_alter_watchconfig_webhooks'), ('marketmanager', '0007_rename_webhook_webhook_url_and_more'), ('marketmanager', '0008_alter_general_options'), ('marketmanager', '0009_remove_watchconfig_fail_webhooks_and_more'), ('marketmanager', '0010_alter_watchconfig_debug_webhooks'), ('marketmanager', '0011_rename_location_watchconfig_structure'), ('marketmanager', '0012_remove_watchconfig_constellation'), ('marketmanager', '0013_watchconfig_managed_app_and_more'), ('marketmanager', '0014_alter_watchconfig_price_typestatistics'), ('marketmanager', '0015_typestatistics_eve_region_and_more'), ('marketmanager', '0016_alter_typestatistics_eve_region'), ('marketmanager', '0017_alter_watchconfig_managed_app_and_more'), ('marketmanager', '0018_remove_typestatistics_buy_5_percent_and_more'), ('marketmanager', '0019_remove_order_escrow_remove_order_source_character_and_more'), ('marketmanager', '0020_alter_order_duration_alter_order_price_and_more'), ('marketmanager', '0021_typestatistics_new_eden'), ('marketmanager', '0022_remove_typestatistics_evetypeeveregiontypestatistic'), ('marketmanager', '0023_alter_typestatistics_eve_region'), ('marketmanager', '0024_remove_typestatistics_new_eden'), ('marketmanager', '0025_statisticsconfig'), ('marketmanager', '0026_alter_publicconfig_options_and_more'), ('marketmanager', '0027_managedwatchconfig_remove_watchconfig_managed_app_and_more'), ('marketmanager', '0028_rename_manged_app_reason_managedwatchconfig_managed_app_reason'), ('marketmanager', '0029_managedwatchconfig_managed_buy_order_and_more'), ('marketmanager', '0030_channel_managedwatchconfig_managed_channels_and_more'), ('marketmanager', '0031_alter_channel_name'), ('marketmanager', '0032_alter_watchconfig_managed_watch_config'), ('marketmanager', '0033_alter_managedwatchconfig_managed_jita_compare_percent'), ('marketmanager', '0034_alter_watchconfig_managed_watch_config'), ('marketmanager', '0035_alter_watchconfig_jita_compare_percent'), ('marketmanager', '0036_watchconfig_last_result_volume_watchconfig_last_run'), ('marketmanager', '0037_alter_general_options'), ('marketmanager', '0038_alter_structure_eve_type_and_more'), ('marketmanager', '0039_alter_order_state'), ('marketmanager', '0040_rename_supplyconfigmodels'), ('marketmanager', '0041_alter_general_options_and_more'), ('marketmanager', '0042_alter_priceconfig_buy_order_and_more'), ('marketmanager', '0043_priceconfig_eve_market_group_alter_priceconfig_price'), ('marketmanager', '0044_priceconfig_minimum'), ('marketmanager', '0045_alter_priceconfig_minimum'), ('marketmanager', '0046_alter_managedsupplyconfig_options_and_more'), ('marketmanager', '0047_alter_structure_eve_type_alter_supplyconfig_eve_type_and_more'), ('marketmanager', '0048_alter_channel_options_and_more'), ('marketmanager', '0049_alter_general_options'), ('marketmanager', '0050_alter_managedsupplyconfig_managed_channels_and_more'), ('marketmanager', '0051_alter_privateconfig_failure_reason'), ('marketmanager', '0052_alter_managedsupplyconfig_options_and_more'), ('marketmanager', '0053_alter_managedsupplyconfig_managed_region_and_more'), ('marketmanager', '0054_remove_marginconfig_structure_type_and_more'), ('marketmanager', '0055_alter_marginconfig_destination_solar_system_and_more'), ('marketmanager', '0056_marginconfig_destination_station_and_more'), ('marketmanager', '0057_marginconfig_freight_cost'), ('marketmanager', '0058_alter_marginconfig_destination_buy_and_more'), ('marketmanager', '0059_alter_managedsupplyconfig_managed_region_and_more')]

    initial = True

    dependencies = [
        ('esi', '0013_squashed_0012_fix_token_type_choices'),
        ('eve_sde', '0017_remove_itemtype_market_group_id_raw'),
        ('eveonline', '0017_alliance_and_corp_names_are_not_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='General',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('basic_market_browser', 'Can access the Standard Market Browser'), ('basic_market_watches', 'Can view all SupplyConfigs and their status'), ('order_highlight_user', "Market orders owned by the user's characters may be highlighted in the standard/basic Market Browser"), ('order_highlight_corporation', 'Market orders owned by any corporation a user is a member of may be highlighted in the standard/basic Market Browser WARNING: This has no checks for Corporation Roles.'), ('advanced_market_browser', 'Can access the Advanced Market Browser'), ('can_add_token_character', 'Can add a Character Token with required scopes'), ('can_add_token_corporation', 'Can add a Corpration Token with required scopes')),
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Channel',
                'verbose_name_plural': 'Channels',
            },
        ),
        migrations.CreateModel(
            name='ManagedSupplyConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('managed_app', models.CharField(blank=True, default='', help_text='The App managing this SupplyConfig', max_length=50, verbose_name='Managed By App')),
                ('managed_app_identifier', models.CharField(blank=True, default='', help_text='An identifier relevant to the App managing this SupplyConfig', max_length=50, verbose_name='Managed App-Identifier')),
                ('managed_app_reason', models.CharField(blank=True, default='', help_text='User Facing reason for this Managed SupplyConfig', max_length=50, verbose_name='Managed App Reason')),
                ('managed_quantity', models.IntegerField(default=1, help_text='Apply a multiplier to the volumes that will be generated', verbose_name='quantity')),
                ('managed_buy_order', models.BooleanField(verbose_name='Buy Order')),
                ('managed_jita_compare_percent', models.DecimalField(decimal_places=0, default=Decimal('0'), help_text='If set ignores Flat price value', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='Jita Comparison %')),
                ('managed_channels', models.ManyToManyField(blank=True, to='marketmanager.channel', verbose_name='Channels')),
                ('managed_debug_channels', models.ManyToManyField(blank=True, help_text='Primarily for Testing/Debugging Purposes. This webhook will receive updates on SupplyConfigs that _dont_ notify. Because their Configs didnt Meet/Breach.', related_name='+', to='marketmanager.channel', verbose_name='Debug Channels')),
            ],
            options={
                'verbose_name': 'Managed Supply Config',
                'verbose_name_plural': 'Managed Supply Configs',
            },
        ),
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('structure_id', models.PositiveBigIntegerField(primary_key=True, serialize=False, verbose_name='Structure ID')),
                ('name', models.CharField(max_length=60, verbose_name='Name')),
                ('owner_id', models.IntegerField(verbose_name='Owner Corporation ID')),
                ('pull_market', models.BooleanField(default=True, help_text='Useful to ignore specific structures for _reasons_', verbose_name='Pull Market Orders')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('eve_type', models.ForeignKey(limit_choices_to={'eve_group__id__in': [15, 1657], 'published': 1}, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='eve_sde.itemtype', verbose_name='Type')),
                ('solar_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='eve_sde.solarsystem', verbose_name='Solar System')),
            ],
        ),
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('url', models.URLField(verbose_name='URL')),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_fifth_percentile', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Buy 5th Percentile')),
                ('sell_fifth_percentile', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Sell 5th Percentile')),
                ('buy_weighted_average', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Buy Weighted Average')),
                ('sell_weighted_average', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Sell Weighted Average')),
                ('buy_median', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Buy Median')),
                ('sell_median', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Sell Median')),
                ('eve_region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='eve_sde.region', verbose_name='Region')),
                ('eve_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eve_sde.itemtype', verbose_name='Type')),
            ],
            options={
                'verbose_name': 'Item Type Statistics',
                'verbose_name_plural': 'Item Types Statistics',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='SupplyConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_order', models.BooleanField(verbose_name='Buy Order')),
                ('volume', models.IntegerField(default=1, help_text='Set to Zero to check ANY/EVERY order against Price', verbose_name='Volume')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Set to Zero to skip this filter', max_digits=15, verbose_name='Price')),
                ('jita_compare_percent', models.DecimalField(decimal_places=0, default=Decimal('0'), help_text='If set ignores Flat price value', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='Jita Comparison %')),
                ('last_run', models.DateTimeField(blank=True, null=True, verbose_name='Last Task Runtime')),
                ('last_result_volume', models.IntegerField(blank=True, help_text='The Volume returned the last time this WatchConfig was run', null=True, verbose_name='Last Result Volume')),
                ('channels', models.ManyToManyField(blank=True, to='marketmanager.channel', verbose_name='Channels')),
                ('debug_channels', models.ManyToManyField(blank=True, help_text='Primarily for Testing/Debugging Purposes. This webhook will receive updates on SupplyConfigs that _dont_ notify. Because their Configs didnt Meet/Breach.', related_name='+', to='marketmanager.channel', verbose_name='Debug Channels')),
                ('debug_webhooks', models.ManyToManyField(blank=True, help_text='Primarily for Testing/Debugging Purposes. This webhook will receive updates on SupplyConfigs that _dont_ notify. Because their Configs didnt Meet/Breach.', related_name='+', to='marketmanager.webhook', verbose_name='Debug Webhook')),
                ('eve_type', models.ForeignKey(limit_choices_to={'eve_market_group__isnull': False, 'published': 1}, on_delete=django.db.models.deletion.CASCADE, to='eve_sde.itemtype', verbose_name='EVE Type')),
                ('managed_supply_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='marketmanager.managedsupplyconfig', verbose_name='Managed Watch Configs')),
                ('region', models.ManyToManyField(blank=True, related_name='+', to='eve_sde.region', verbose_name='Region')),
                ('solar_system', models.ManyToManyField(blank=True, to='eve_sde.solarsystem', verbose_name='Solar System')),
                ('structure', models.ManyToManyField(blank=True, to='marketmanager.structure', verbose_name='Structure')),
                ('structure_type', models.ManyToManyField(blank=True, help_text='Filter by structure Type/Size/Docking (ie, forts/keeps for cap fuel)', related_name='+', to='eve_sde.itemtype', verbose_name='Structure Type Filter')),
                ('webhooks', models.ManyToManyField(blank=True, to='marketmanager.webhook', verbose_name='Webhooks')),
            ],
            options={
                'verbose_name': 'Supply Config',
                'verbose_name_plural': 'Supply Configs',
            },
        ),
        migrations.CreateModel(
            name='StatisticsConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculate_regions', models.ManyToManyField(to='eve_sde.region', verbose_name='TypeStatistics Calculation Regions')),
            ],
            options={
                'verbose_name': 'TypeStatistics Calculation Configuration',
            },
        ),
        migrations.CreateModel(
            name='PublicConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fetch_regions', models.ManyToManyField(related_name='+', to='eve_sde.region', verbose_name='Fetch Regions')),
            ],
            options={
                'verbose_name': 'Public Market Configuration',
            },
        ),
        migrations.CreateModel(
            name='PrivateConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('failed', models.BooleanField(verbose_name='Disabled due to Failure, Check reason, adjust config and re-enable')),
                ('failure_reason', models.CharField(blank=True, default='Failure Reason', max_length=100, verbose_name='Failure Reason')),
                ('token', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='esi.token', verbose_name='ESI Token')),
                ('valid_corporations', models.ManyToManyField(blank=True, to='eveonline.evecorporationinfo', verbose_name='Valid Corporation Markets for this Token')),
                ('valid_structures', models.ManyToManyField(blank=True, to='marketmanager.structure', verbose_name='Valid Structure Markets for this Token')),
            ],
            options={
                'verbose_name': 'Private Market Configuration',
                'verbose_name_plural': 'Private Market Configurations',
            },
        ),
        migrations.CreateModel(
            name='PriceConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_order', models.BooleanField(default=False, verbose_name='Buy Order')),
                ('scalp', models.BooleanField(default=False, help_text='True for Scalp, False for Bargain', verbose_name='Scalp Finder?')),
                ('minimum', models.DecimalField(decimal_places=2, default=Decimal('1000000'), help_text='Minimum isk to consider an order at, Default: 1M', max_digits=15, verbose_name='Minimum Price')),
                ('jita_compare_percent', models.DecimalField(decimal_places=0, default=Decimal('0'), help_text='If set ignores Flat price value', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='Jita Comparison %')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='WARNING: Use Jita% when possible, this sets a flat price for ALL items included in this Config. Possibly useful for Caps/Soups', max_digits=15, verbose_name='Price')),
                ('last_run', models.DateTimeField(blank=True, null=True, verbose_name='Last Task Runtime')),
                ('channels', models.ManyToManyField(blank=True, to='marketmanager.channel', verbose_name='Channels')),
                ('debug_channels', models.ManyToManyField(blank=True, help_text='Primarily for Testing/Debugging Purposes. This webhook will receive updates on PriceConfigs that _dont_ notify. Because their Configs didnt Meet/Breach.', related_name='+', to='marketmanager.channel', verbose_name='Debug Channels')),
                ('debug_webhooks', models.ManyToManyField(blank=True, help_text='Primarily for Testing/Debugging Purposes. This webhook will receive updates on PriceConfigs that _dont_ notify. Because their Configs didnt Meet/Breach.', related_name='+', to='marketmanager.webhook', verbose_name='Debug Webhook')),
                ('eve_group', models.ManyToManyField(blank=True, to='eve_sde.itemgroup', verbose_name='EVE Inventory Group')),
                ('eve_market_group', models.ManyToManyField(blank=True, to='eve_sde.itemmarketgroup', verbose_name='EVE Market Group')),
                ('eve_type', models.ManyToManyField(blank=True, to='eve_sde.itemtype', verbose_name='EVE Type')),
                ('region', models.ManyToManyField(blank=True, related_name='+', to='eve_sde.region', verbose_name='Region')),
                ('solar_system', models.ManyToManyField(blank=True, to='eve_sde.solarsystem', verbose_name='Solar System')),
                ('structure', models.ManyToManyField(blank=True, to='marketmanager.structure', verbose_name='Structure')),
                ('structure_type', models.ManyToManyField(blank=True, help_text='Filter by structure Type/Size/Docking (ie, forts/keeps for cap fuel)', related_name='+', to='eve_sde.itemtype', verbose_name='Structure Type Filter')),
                ('webhooks', models.ManyToManyField(blank=True, to='marketmanager.webhook', verbose_name='Webhooks')),
            ],
            options={
                'verbose_name': 'Price Config',
                'verbose_name_plural': 'Price Configs',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.PositiveBigIntegerField(help_text='Unique order ID', primary_key=True, serialize=False, verbose_name='Order ID')),
                ('duration', models.PositiveSmallIntegerField(help_text='Number of days the order was valid for (starting from the issued date). An order expires at time issued + duration', verbose_name='Duration')),
                ('is_buy_order', models.BooleanField(db_index=True, default=False, help_text='True if the order is a bid (buy) order', verbose_name='Buy Order')),
                ('issued', models.DateTimeField(help_text='Date and time when this order was issued', verbose_name='Issued')),
                ('location_id', models.PositiveBigIntegerField(help_text='ID of the location where order was placed', verbose_name='Location ID')),
                ('min_volume', models.PositiveIntegerField(blank=True, help_text='For buy orders, the minimum quantity that will be accepted in a matching sell order', null=True, verbose_name='Minimum Volume')),
                ('price', models.DecimalField(decimal_places=2, help_text='Cost per unit for this order', max_digits=15, verbose_name='Price')),
                ('range', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('10', '10'), ('20', '20'), ('30', '30'), ('40', '40'), ('region', 'Region'), ('solarsystem', 'Solar System'), ('station', 'Station')], help_text='Valid order range, numbers are ranges in jumps', max_length=12, verbose_name='Order Range')),
                ('volume_remain', models.PositiveIntegerField(help_text='Quantity of items still required or offered', verbose_name='Volume Remaining')),
                ('is_corporation', models.BooleanField(default=False, help_text='Signifies whether the buy/sell order was placed on behalf of a corporation.', verbose_name='Is Corporation')),
                ('wallet_division', models.PositiveSmallIntegerField(blank=True, help_text='The corporation wallet division used for this order.', null=True, verbose_name='Wallet Division')),
                ('state', models.CharField(blank=True, choices=[('', ''), ('cancelled', 'Cancelled'), ('expired ', 'Expired')], help_text='Current order state, Only valid for Authenticated order History. Will not update from Public Market Data.', max_length=10, null=True, verbose_name='Order State')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('eve_region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='eve_sde.region', verbose_name='Region')),
                ('eve_solar_system', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eve_sde.solarsystem', verbose_name='System')),
                ('eve_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eve_sde.itemtype', verbose_name='Type')),
                ('issued_by_character', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eveonline.evecharacter', verbose_name='Character')),
                ('issued_by_corporation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eveonline.evecorporationinfo', verbose_name='Corporation')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='MarginConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importing', models.BooleanField(default=True, help_text='True for Importing, False for Exporting', verbose_name='Import Items?')),
                ('source_buy', models.BooleanField(default=False, help_text='Buy orders in the Source?, False for Sell', verbose_name='Source Buy Orders?')),
                ('destination_buy', models.BooleanField(default=False, help_text='Buy orders in the Destination?, False for Sell', verbose_name='Destination Buy Orders?')),
                ('margin_percent', models.DecimalField(decimal_places=0, default=Decimal('5'), help_text='% difference of an order to highlight', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='% Margin')),
                ('freight_cost', models.IntegerField(default=0, help_text='isk/m3 to optionally add to imported item prices', verbose_name='Import Cost (ISK/m3)')),
                ('last_run', models.DateTimeField(blank=True, null=True, verbose_name='Last Task Runtime')),
                ('channels', models.ManyToManyField(blank=True, related_name='+', to='marketmanager.channel', verbose_name='Channels')),
                ('debug_channels', models.ManyToManyField(blank=True, help_text='Primarily for Testing/Debugging Purposes. This webhook will receive updates on MarginConfigs that _dont_ notify. Because their Configs didnt Meet/Breach.', related_name='+', to='marketmanager.channel', verbose_name='Debug Channels')),
                ('debug_webhooks', models.ManyToManyField(blank=True, help_text='Primarily for Testing/Debugging Purposes. This webhook will receive updates on MarginConfigs that _dont_ notify. Because their Configs didnt Meet/Breach.', related_name='+', to='marketmanager.webhook', verbose_name='Debug Webhook')),
                ('destination_region', models.ManyToManyField(blank=True, related_name='+', to='eve_sde.region', verbose_name='Destination Region')),
                ('destination_solar_system', models.ManyToManyField(blank=True, related_name='+', to='eve_sde.solarsystem', verbose_name='Destination Solar System')),
                ('destination_station', models.ManyToManyField(blank=True, related_name='+', to='eve_sde.npcstation', verbose_name='Destination Station')),
                ('destination_structure', models.ManyToManyField(blank=True, related_name='+', to='marketmanager.structure', verbose_name='Destination Structure')),
                ('eve_group', models.ManyToManyField(blank=True, related_name='+', to='eve_sde.itemgroup', verbose_name='EVE Inventory Group')),
                ('eve_market_group', models.ManyToManyField(blank=True, related_name='+', to='eve_sde.itemmarketgroup', verbose_name='EVE Market Group')),
                ('eve_type', models.ManyToManyField(blank=True, related_name='+', to='eve_sde.itemtype', verbose_name='EVE Type')),
                ('source_region', models.ManyToManyField(blank=True, related_name='+', to='eve_sde.region', verbose_name='Source Region')),
                ('source_solar_system', models.ManyToManyField(blank=True, related_name='+', to='eve_sde.solarsystem', verbose_name='Source Solar System')),
                ('source_station', models.ManyToManyField(blank=True, related_name='+', to='eve_sde.npcstation', verbose_name='Source Station')),
                ('source_structure', models.ManyToManyField(blank=True, related_name='+', to='marketmanager.structure', verbose_name='Source Structure')),
                ('webhooks', models.ManyToManyField(blank=True, related_name='+', to='marketmanager.webhook', verbose_name='Webhooks')),
            ],
            options={
                'verbose_name': 'Margin Configs',
                'verbose_name_plural': 'Margin Configs',
            },
        ),
        migrations.AddField(
            model_name='managedsupplyconfig',
            name='managed_debug_webhooks',
            field=models.ManyToManyField(blank=True, help_text='Primarily for Testing/Debugging Purposes. This webhook will receive updates on Supplyonfigs that _dont_ notify. Because their Configs didnt Meet/Breach.', related_name='+', to='marketmanager.webhook', verbose_name='Debug Webhook'),
        ),
        migrations.AddField(
            model_name='managedsupplyconfig',
            name='managed_region',
            field=models.ManyToManyField(blank=True, related_name='+', to='eve_sde.region', verbose_name='Region'),
        ),
        migrations.AddField(
            model_name='managedsupplyconfig',
            name='managed_solar_system',
            field=models.ManyToManyField(blank=True, to='eve_sde.solarsystem', verbose_name='Solar System'),
        ),
        migrations.AddField(
            model_name='managedsupplyconfig',
            name='managed_structure',
            field=models.ManyToManyField(blank=True, to='marketmanager.structure', verbose_name='Structure'),
        ),
        migrations.AddField(
            model_name='managedsupplyconfig',
            name='managed_structure_type',
            field=models.ManyToManyField(blank=True, help_text='Filter by structure Type/Size/Docking (ie, forts/keeps for cap fuel)', to='eve_sde.itemtype', verbose_name='Structure Type Filter'),
        ),
        migrations.AddField(
            model_name='managedsupplyconfig',
            name='managed_webhooks',
            field=models.ManyToManyField(blank=True, to='marketmanager.webhook', verbose_name='Webhooks'),
        ),
    ]
