# Generated by Django 5.2.12 on 2026-03-20 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eve_sde', '0018_blueprintactivity_blueprintactivityproduct_and_more'),
        ('marketmanager', '0060_v1_2_0'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marginconfig',
            old_name='eve_group',
            new_name='item_group',
        ),
        migrations.RenameField(
            model_name='marginconfig',
            old_name='eve_market_group',
            new_name='item_market_group',
        ),
        migrations.RenameField(
            model_name='marginconfig',
            old_name='eve_type',
            new_name='item_type',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='eve_type',
            new_name='item_type',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='eve_region',
            new_name='region',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='eve_solar_system',
            new_name='solar_system',
        ),
        migrations.RenameField(
            model_name='priceconfig',
            old_name='eve_group',
            new_name='item_group',
        ),
        migrations.RenameField(
            model_name='priceconfig',
            old_name='eve_market_group',
            new_name='item_market_group',
        ),
        migrations.RenameField(
            model_name='priceconfig',
            old_name='eve_type',
            new_name='item_type',
        ),
        migrations.RenameField(
            model_name='typestatistics',
            old_name='eve_type',
            new_name='item_type',
        ),
        migrations.RenameField(
            model_name='typestatistics',
            old_name='eve_region',
            new_name='region',
        ),
        migrations.AlterField(
            model_name='structure',
            name='eve_type',
            field=models.ForeignKey(limit_choices_to={'item_group__id__in': [15, 1657], 'published': 1}, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='eve_sde.itemtype', verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='supplyconfig',
            name='eve_type',
            field=models.ForeignKey(limit_choices_to={'item_group__isnull': False, 'published': 1}, on_delete=django.db.models.deletion.CASCADE, to='eve_sde.itemtype', verbose_name='EVE Type'),
        ),
    ]
