# Generated by Django 5.2.12 on 2026-03-20 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketmanager', '0061_rename_eve_group_marginconfig_item_group_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='structure',
            old_name='eve_type',
            new_name='item_type',
        ),
        migrations.RenameField(
            model_name='supplyconfig',
            old_name='eve_type',
            new_name='item_type',
        ),
    ]
