# Generated by Django 5.2.17 on 2026-09-13 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penguin_bridge', '0004_penguinpingchannel'),
    ]

    operations = [
        migrations.CreateModel(
            name='PenguinBuildJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_user_id', models.BigIntegerField(db_index=True)),
                ('owner_name', models.CharField(blank=True, default='', max_length=100)),
                ('corp_id', models.BigIntegerField(db_index=True, default=0)),
                ('alliance_id', models.BigIntegerField(db_index=True, default=0)),
                ('mode', models.CharField(choices=[('corp', 'Corp Project'), ('divisional', 'Divisional Manufacturing')], db_index=True, default='corp', max_length=16)),
                ('tier', models.CharField(choices=[('d0', 'D0 — quick builds'), ('d1', 'D1 — capital components'), ('d2', 'D2 — T2 / advanced components'), ('d3', 'D3 — final builds')], db_index=True, default='d0', max_length=4)),
                ('status', models.CharField(choices=[('open', 'Open'), ('claimed', 'Claimed'), ('in_progress', 'In progress'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], db_index=True, default='open', max_length=16)),
                ('type_id', models.IntegerField(default=0)),
                ('type_name', models.CharField(max_length=255)),
                ('quantity', models.BigIntegerField(default=1)),
                ('blueprint_type_id', models.IntegerField(blank=True, null=True)),
                ('source_kind', models.CharField(choices=[('manual', 'Manual'), ('fit', 'From a fit'), ('auto_restock', 'Auto-restock (corp minimum)')], default='manual', max_length=16)),
                ('source_ref', models.CharField(blank=True, default='', max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('corp_profit_margin_pct', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('builder_share_isk', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('corp_share_isk', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('claimed_by_user_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('claimed_by_name', models.CharField(blank=True, default='', max_length=100)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('expected_delivery_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'permissions': [('can_manage_build_jobs', 'Can create/manage corp and divisional build jobs')],
                'default_permissions': (),
                'indexes': [models.Index(fields=['corp_id', 'mode', 'tier', 'status'], name='penguin_bri_corp_id_974f81_idx'), models.Index(fields=['alliance_id', 'mode', 'tier', 'status'], name='penguin_bri_allianc_972254_idx'), models.Index(fields=['claimed_by_user_id', 'status'], name='penguin_bri_claimed_8ad467_idx')],
            },
        ),
    ]
