# Generated by Django 5.2.17 on 2026-09-14 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penguin_bridge', '0005_penguinbuildjob'),
    ]

    operations = [
        migrations.CreateModel(
            name='PenguinFeedbackScreenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(db_index=True)),
                ('username', models.CharField(blank=True, default='', max_length=150)),
                ('main_character_name', models.CharField(blank=True, default='', max_length=100)),
                ('app_version', models.CharField(blank=True, default='', max_length=32)),
                ('note', models.TextField(blank=True, default='')),
                ('image', models.BinaryField()),
                ('content_type', models.CharField(default='image/png', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
