# Generated by Django 5.1.6 on 2025-03-05 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srp', '0004_on_delete'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='srpfleetmain',
            options={'default_permissions': (), 'permissions': (('access_srp', 'Can access SRP module'), ('add_srpfleetmain', 'Can access SRP module'))},
        ),
    ]
