# Generated by Django 5.1.9 on 2025-05-18 15:43

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationAnnouncement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_name', models.CharField(help_text='Name of the application that issued the announcement', max_length=50)),
                ('announcement_number', models.IntegerField(help_text='Issue number on the notification source')),
                ('announcement_text', models.TextField(help_text='Issue title text displayed on the dashboard', max_length=300)),
                ('announcement_url', models.TextField(max_length=200)),
                ('announcement_hash', models.CharField(default=None, editable=False, help_text='hash of an announcement. Must be nullable for unique comparison.', max_length=64, null=True, unique=True)),
                ('hide_announcement', models.BooleanField(default=False, help_text='Set to true if the announcement should not be displayed on the dashboard')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('application_name', 'announcement_number'), name='functional_pk_applicationissuenumber')],
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
