# Generated by Django 5.2.12 on 2026-03-12 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_status", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicationannouncement",
            name="announcement_hash",
            field=models.CharField(
                default=None,
                editable=False,
                help_text="hash of an announcement.",
                max_length=64,
                unique=True,
            ),
        ),
    ]
