# Generated by Django 5.2.12 on 2026-03-12 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hrapplications", "0008_v5squash"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="application",
            options={
                "permissions": (
                    ("approve_application", "Can approve applications"),
                    ("reject_application", "Can reject applications"),
                )
            },
        ),
        migrations.AlterModelOptions(
            name="applicationform",
            options={"permissions": ()},
        ),
        migrations.AlterField(
            model_name="applicationquestion",
            name="help_text",
            field=models.CharField(blank=True, default="", max_length=254),
        ),
    ]
