# Generated by Django 5.1.6 on 2025-03-05 00:50

import django.db.migrations.operations.special
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('phpbb3', '0001_initial'), ('phpbb3', '0002_service_permissions')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Phpbb3User',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='phpbb3', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('username', models.CharField(max_length=254)),
            ],
            options={
                'default_permissions': (),
                'permissions': (('access_phpbb3', 'Can access the phpBB3 service'),),
            },
        ),
    ]
