# Generated by Django 5.1.6 on 2025-03-05 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mumble', '0013_connection_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mumbleuser',
            name='certhash',
            field=models.CharField(blank=True, default='', editable=False, help_text='Hash of Mumble client certificate as presented when user authenticates', max_length=254, verbose_name='Certificate Hash'),
        ),
        migrations.AlterField(
            model_name='mumbleuser',
            name='groups',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='mumbleuser',
            name='release',
            field=models.TextField(blank=True, default='', editable=False, help_text='Client release. For official releases, this equals the version. For snapshots and git compiles, this will be something else.', max_length=254, verbose_name='Mumble Release'),
        ),
    ]
