# Generated by Django 5.2.11 on 2026-03-11 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mumble', '0016_idlerhandler_alter_mumbleuser_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mumbleserverserver',
            name='secret',
            field=models.CharField(help_text='ice_secret_read in murmur.ini, used for authenticating with the Mumble Server', max_length=50, verbose_name='ICE Secret'),
        ),
        migrations.AlterField(
            model_name='mumbleserverserver',
            name='slice',
            field=models.CharField(choices=[('MumbleServer_1_6_870.ice', 'MumbleServer.ice (Mumble-Server 1.6.870)'), ('MumbleServer_1_5_857.ice', 'MumbleServer.ice (Mumble-Server 1.5.857)'), ('Murmur_1_4_287.ice', 'Murmur.ice (Murmur 1.4.287)'), ('Murmur_1_4_274.ice', 'Murmur.ice (Murmur 1.4.274)'), ('Murmur_1_3_4.ice', 'Murmur.ice (Murmur 1.3.4)')], default='MumbleServer_1_6_870.ice', help_text='The slice file to use for connecting to the Mumble Server. This should match the version of the Mumble Server you are running.', max_length=32),
        ),
        migrations.AlterField(
            model_name='mumbleserverserver',
            name='watchdog',
            field=models.SmallIntegerField(default=30, help_text='Interval in seconds for Authenticator to check/reapply connection to Mumble Server', verbose_name='Watchdog Interval'),
        ),
    ]
