# Generated by Django 5.2.11 on 2026-03-11 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mumble', '0017_alter_mumbleserverserver_secret_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tempuser',
            name='expires',
        ),
    ]
