"""phase5_6_wh_identity_audit

Revision ID: 43b5e6a505ca
Revises: 68f51ba454ea
Create Date: 2026-06-20 12:50:31.391912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '43b5e6a505ca'
down_revision: Union[str, None] = '68f51ba454ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emums_audit_security_flags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.BigInteger(), nullable=False),
    sa.Column('character_name', sa.String(length=128), nullable=False),
    sa.Column('flag_key', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emums_audit_security_flags_character_id'), 'emums_audit_security_flags', ['character_id'], unique=False)
    op.create_index(op.f('ix_emums_audit_security_flags_created_at'), 'emums_audit_security_flags', ['created_at'], unique=False)
    op.create_index(op.f('ix_emums_audit_security_flags_flag_key'), 'emums_audit_security_flags', ['flag_key'], unique=False)
    op.create_index(op.f('ix_emums_audit_security_flags_resolved'), 'emums_audit_security_flags', ['resolved'], unique=False)
    op.create_table('emums_character_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.BigInteger(), nullable=False),
    sa.Column('item_id', sa.BigInteger(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('type_name', sa.String(length=256), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.BigInteger(), nullable=False),
    sa.Column('flag', sa.String(length=32), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emums_character_assets_character_id'), 'emums_character_assets', ['character_id'], unique=False)
    op.create_index(op.f('ix_emums_character_assets_item_id'), 'emums_character_assets', ['item_id'], unique=True)
    op.create_index(op.f('ix_emums_character_assets_type_id'), 'emums_character_assets', ['type_id'], unique=False)
    op.create_table('emums_character_wallet_journals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.BigInteger(), nullable=False),
    sa.Column('journal_id', sa.BigInteger(), nullable=False),
    sa.Column('ref_type', sa.String(length=64), nullable=False),
    sa.Column('amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('balance', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('first_party_id', sa.BigInteger(), nullable=True),
    sa.Column('second_party_id', sa.BigInteger(), nullable=True),
    sa.Column('reason', sa.String(length=512), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emums_character_wallet_journals_character_id'), 'emums_character_wallet_journals', ['character_id'], unique=False)
    op.create_index(op.f('ix_emums_character_wallet_journals_journal_id'), 'emums_character_wallet_journals', ['journal_id'], unique=True)
    op.create_index(op.f('ix_emums_character_wallet_journals_recorded_at'), 'emums_character_wallet_journals', ['recorded_at'], unique=False)
    op.create_index(op.f('ix_emums_character_wallet_journals_ref_type'), 'emums_character_wallet_journals', ['ref_type'], unique=False)
    op.create_index(op.f('ix_emums_character_wallet_journals_second_party_id'), 'emums_character_wallet_journals', ['second_party_id'], unique=False)
    op.create_table('emums_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('is_hidden', sa.Boolean(), nullable=False),
    sa.Column('is_open', sa.Boolean(), nullable=False),
    sa.Column('discord_role_id', sa.String(length=32), nullable=False),
    sa.Column('permissions_json', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emums_groups_name'), 'emums_groups', ['name'], unique=True)
    op.create_table('emums_service_sync_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('discord_bot_token', sa.Text(), nullable=False),
    sa.Column('discord_guild_id', sa.String(length=32), nullable=False),
    sa.Column('discord_nickname_format', sa.String(length=128), nullable=False),
    sa.Column('mumble_server_json', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('emums_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('priority_weight', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(length=24), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emums_states_name'), 'emums_states', ['name'], unique=True)
    op.create_index(op.f('ix_emums_states_priority_weight'), 'emums_states', ['priority_weight'], unique=False)
    op.create_table('emums_user_service_sync',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.BigInteger(), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=False),
    sa.Column('discord_roles_json', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emums_user_service_sync_character_id'), 'emums_user_service_sync', ['character_id'], unique=True)
    op.create_table('emums_wh_maps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('creator_character_id', sa.BigInteger(), nullable=False),
    sa.Column('creator_character_name', sa.String(length=128), nullable=False),
    sa.Column('alliance_id', sa.BigInteger(), nullable=True),
    sa.Column('active_tracking_character_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emums_wh_maps_alliance_id'), 'emums_wh_maps', ['alliance_id'], unique=False)
    op.create_index(op.f('ix_emums_wh_maps_creator_character_id'), 'emums_wh_maps', ['creator_character_id'], unique=False)
    op.create_table('emums_character_group_joins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.BigInteger(), nullable=False),
    sa.Column('character_name', sa.String(length=128), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('granted_by_character_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['emums_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emums_character_group_joins_character_id'), 'emums_character_group_joins', ['character_id'], unique=False)
    op.create_index(op.f('ix_emums_character_group_joins_group_id'), 'emums_character_group_joins', ['group_id'], unique=False)
    op.create_index(op.f('ix_emums_character_group_joins_status'), 'emums_character_group_joins', ['status'], unique=False)
    op.create_table('emums_state_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state_id', sa.Integer(), nullable=False),
    sa.Column('allowed_alliance_ids_json', sa.Text(), nullable=False),
    sa.Column('allowed_corporation_ids_json', sa.Text(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['state_id'], ['emums_states.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emums_state_rules_state_id'), 'emums_state_rules', ['state_id'], unique=False)
    op.create_table('emums_wh_systems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('map_id', sa.Integer(), nullable=False),
    sa.Column('solar_system_id', sa.Integer(), nullable=False),
    sa.Column('system_name', sa.String(length=128), nullable=False),
    sa.Column('system_signature', sa.String(length=32), nullable=False),
    sa.Column('wh_class', sa.String(length=16), nullable=False),
    sa.Column('space_type', sa.String(length=16), nullable=False),
    sa.Column('effect', sa.String(length=64), nullable=False),
    sa.Column('statics_json', sa.Text(), nullable=False),
    sa.Column('pos_x', sa.Float(), nullable=False),
    sa.Column('pos_y', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['map_id'], ['emums_wh_maps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emums_wh_systems_map_id'), 'emums_wh_systems', ['map_id'], unique=False)
    op.create_index(op.f('ix_emums_wh_systems_solar_system_id'), 'emums_wh_systems', ['solar_system_id'], unique=False)
    op.create_index(op.f('ix_emums_wh_systems_system_signature'), 'emums_wh_systems', ['system_signature'], unique=False)
    op.create_table('emums_wh_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('map_id', sa.Integer(), nullable=False),
    sa.Column('source_node_id', sa.Integer(), nullable=False),
    sa.Column('target_node_id', sa.Integer(), nullable=False),
    sa.Column('wh_type', sa.String(length=32), nullable=False),
    sa.Column('mass_status', sa.String(length=16), nullable=False),
    sa.Column('eol', sa.Boolean(), nullable=False),
    sa.Column('signature_in', sa.String(length=32), nullable=False),
    sa.Column('signature_out', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['map_id'], ['emums_wh_maps.id'], ),
    sa.ForeignKeyConstraint(['source_node_id'], ['emums_wh_systems.id'], ),
    sa.ForeignKeyConstraint(['target_node_id'], ['emums_wh_systems.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emums_wh_connections_map_id'), 'emums_wh_connections', ['map_id'], unique=False)
    op.create_index(op.f('ix_emums_wh_connections_source_node_id'), 'emums_wh_connections', ['source_node_id'], unique=False)
    op.create_index(op.f('ix_emums_wh_connections_target_node_id'), 'emums_wh_connections', ['target_node_id'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    op.drop_index(op.f('ix_emums_wh_connections_target_node_id'), table_name='emums_wh_connections')
    op.drop_index(op.f('ix_emums_wh_connections_source_node_id'), table_name='emums_wh_connections')
    op.drop_index(op.f('ix_emums_wh_connections_map_id'), table_name='emums_wh_connections')
    op.drop_table('emums_wh_connections')
    op.drop_index(op.f('ix_emums_wh_systems_system_signature'), table_name='emums_wh_systems')
    op.drop_index(op.f('ix_emums_wh_systems_solar_system_id'), table_name='emums_wh_systems')
    op.drop_index(op.f('ix_emums_wh_systems_map_id'), table_name='emums_wh_systems')
    op.drop_table('emums_wh_systems')
    op.drop_index(op.f('ix_emums_state_rules_state_id'), table_name='emums_state_rules')
    op.drop_table('emums_state_rules')
    op.drop_index(op.f('ix_emums_character_group_joins_status'), table_name='emums_character_group_joins')
    op.drop_index(op.f('ix_emums_character_group_joins_group_id'), table_name='emums_character_group_joins')
    op.drop_index(op.f('ix_emums_character_group_joins_character_id'), table_name='emums_character_group_joins')
    op.drop_table('emums_character_group_joins')
    op.drop_index(op.f('ix_emums_wh_maps_creator_character_id'), table_name='emums_wh_maps')
    op.drop_index(op.f('ix_emums_wh_maps_alliance_id'), table_name='emums_wh_maps')
    op.drop_table('emums_wh_maps')
    op.drop_index(op.f('ix_emums_user_service_sync_character_id'), table_name='emums_user_service_sync')
    op.drop_table('emums_user_service_sync')
    op.drop_index(op.f('ix_emums_states_priority_weight'), table_name='emums_states')
    op.drop_index(op.f('ix_emums_states_name'), table_name='emums_states')
    op.drop_table('emums_states')
    op.drop_table('emums_service_sync_config')
    op.drop_index(op.f('ix_emums_groups_name'), table_name='emums_groups')
    op.drop_table('emums_groups')
    op.drop_index(op.f('ix_emums_character_wallet_journals_second_party_id'), table_name='emums_character_wallet_journals')
    op.drop_index(op.f('ix_emums_character_wallet_journals_ref_type'), table_name='emums_character_wallet_journals')
    op.drop_index(op.f('ix_emums_character_wallet_journals_recorded_at'), table_name='emums_character_wallet_journals')
    op.drop_index(op.f('ix_emums_character_wallet_journals_journal_id'), table_name='emums_character_wallet_journals')
    op.drop_index(op.f('ix_emums_character_wallet_journals_character_id'), table_name='emums_character_wallet_journals')
    op.drop_table('emums_character_wallet_journals')
    op.drop_index(op.f('ix_emums_character_assets_type_id'), table_name='emums_character_assets')
    op.drop_index(op.f('ix_emums_character_assets_item_id'), table_name='emums_character_assets')
    op.drop_index(op.f('ix_emums_character_assets_character_id'), table_name='emums_character_assets')
    op.drop_table('emums_character_assets')
    op.drop_index(op.f('ix_emums_audit_security_flags_resolved'), table_name='emums_audit_security_flags')
    op.drop_index(op.f('ix_emums_audit_security_flags_flag_key'), table_name='emums_audit_security_flags')
    op.drop_index(op.f('ix_emums_audit_security_flags_created_at'), table_name='emums_audit_security_flags')
    op.drop_index(op.f('ix_emums_audit_security_flags_character_id'), table_name='emums_audit_security_flags')
    op.drop_table('emums_audit_security_flags')
