"""initial baseline

Revision ID: 68f51ba454ea
Revises: 
Create Date: 2026-06-20 12:40:05.742909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68f51ba454ea'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emums_appraisal_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('share_token', sa.String(length=32), nullable=False),
    sa.Column('paste_text', sa.Text(), nullable=False),
    sa.Column('sell_market', sa.String(length=32), nullable=False),
    sa.Column('buy_market', sa.String(length=32), nullable=False),
    sa.Column('structure_id', sa.BigInteger(), nullable=True),
    sa.Column('result_json', sa.Text(), nullable=False),
    sa.Column('created_by_character_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emums_appraisal_reports_created_at'), 'emums_appraisal_reports', ['created_at'], unique=False)
    op.create_index(op.f('ix_emums_appraisal_reports_share_token'), 'emums_appraisal_reports', ['share_token'], unique=True)
    op.create_table('emums_audit_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.BigInteger(), nullable=False),
    sa.Column('character_name', sa.String(length=128), nullable=False),
    sa.Column('corporation_name', sa.String(length=128), nullable=False),
    sa.Column('wallet_balance_isk', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('skill_points', sa.BigInteger(), nullable=False),
    sa.Column('assets_value_isk', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('snapshot_json', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emums_audit_profiles_character_id'), 'emums_audit_profiles', ['character_id'], unique=True)
    op.create_table('emums_authed_structures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('structure_id', sa.BigInteger(), nullable=False),
    sa.Column('structure_name', sa.String(length=256), nullable=False),
    sa.Column('system_name', sa.String(length=128), nullable=False),
    sa.Column('has_market', sa.Boolean(), nullable=False),
    sa.Column('has_reprocessing', sa.Boolean(), nullable=False),
    sa.Column('owner_character_id', sa.BigInteger(), nullable=False),
    sa.Column('solar_system_id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emums_authed_structures_structure_id'), 'emums_authed_structures', ['structure_id'], unique=True)
    op.create_table('emums_blueprint_public_contracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.BigInteger(), nullable=False),
    sa.Column('blueprint_name', sa.String(length=256), nullable=False),
    sa.Column('seller_name', sa.String(length=128), nullable=False),
    sa.Column('location', sa.String(length=256), nullable=False),
    sa.Column('price_isk', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('runs', sa.Integer(), nullable=False),
    sa.Column('material_efficiency', sa.Integer(), nullable=False),
    sa.Column('time_efficiency', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emums_blueprint_public_contracts_contract_id'), 'emums_blueprint_public_contracts', ['contract_id'], unique=False)
    op.create_table('emums_buyback_quotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('share_token', sa.String(length=32), nullable=False),
    sa.Column('paste_text', sa.Text(), nullable=False),
    sa.Column('fee_pct', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('sell_market', sa.String(length=32), nullable=False),
    sa.Column('structure_id', sa.BigInteger(), nullable=True),
    sa.Column('contract_value_isk', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('result_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emums_buyback_quotes_created_at'), 'emums_buyback_quotes', ['created_at'], unique=False)
    op.create_index(op.f('ix_emums_buyback_quotes_share_token'), 'emums_buyback_quotes', ['share_token'], unique=True)
    op.create_table('emums_character_skill_levels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.BigInteger(), nullable=False),
    sa.Column('character_name', sa.String(length=128), nullable=False),
    sa.Column('skill_type_id', sa.Integer(), nullable=False),
    sa.Column('skill_name', sa.String(length=128), nullable=False),
    sa.Column('trained_level', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('character_id', 'skill_type_id', name='uq_char_skill')
    )
    op.create_index(op.f('ix_emums_character_skill_levels_character_id'), 'emums_character_skill_levels', ['character_id'], unique=False)
    op.create_index(op.f('ix_emums_character_skill_levels_skill_type_id'), 'emums_character_skill_levels', ['skill_type_id'], unique=False)
    op.create_table('emums_corp_market_listings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seller_character_name', sa.String(length=128), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('type_name', sa.String(length=128), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price_isk', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('listing_type', sa.String(length=24), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('structure_name', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emums_corp_market_listings_status'), 'emums_corp_market_listings', ['status'], unique=False)
    op.create_index(op.f('ix_emums_corp_market_listings_type_id'), 'emums_corp_market_listings', ['type_id'], unique=False)
    op.create_table('emums_corp_market_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('buyer_character_name', sa.String(length=128), nullable=False),
    sa.Column('buyer_character_id', sa.BigInteger(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('type_name', sa.String(length=128), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price_isk', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('total_price_isk', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('delivery_location', sa.String(length=256), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('mail_sent_buyer', sa.Boolean(), nullable=False),
    sa.Column('mail_sent_corp', sa.Boolean(), nullable=False),
    sa.Column('mail_error', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emums_corp_market_orders_buyer_character_id'), 'emums_corp_market_orders', ['buyer_character_id'], unique=False)
    op.create_index(op.f('ix_emums_corp_market_orders_status'), 'emums_corp_market_orders', ['status'], unique=False)
    op.create_index(op.f('ix_emums_corp_market_orders_type_id'), 'emums_corp_market_orders', ['type_id'], unique=False)
    op.create_table('emums_dashboard_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('metric_key', sa.String(length=64), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emums_dashboard_snapshots_metric_key'), 'emums_dashboard_snapshots', ['metric_key'], unique=True)
    op.create_table('emums_desktop_backgrounds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=False),
    sa.Column('video_url', sa.String(length=1024), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('emums_fittings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('ship_type_id', sa.Integer(), nullable=False),
    sa.Column('ship_type_name', sa.String(length=128), nullable=False),
    sa.Column('doctrine_slug', sa.String(length=64), nullable=False),
    sa.Column('eft_text', sa.Text(), nullable=False),
    sa.Column('tags_json', sa.Text(), nullable=False),
    sa.Column('public', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emums_fittings_doctrine_slug'), 'emums_fittings', ['doctrine_slug'], unique=False)
    op.create_table('emums_hr_blacklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_name', sa.String(length=128), nullable=False),
    sa.Column('character_id', sa.BigInteger(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('added_by', sa.String(length=128), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emums_hr_blacklist_character_name'), 'emums_hr_blacklist', ['character_name'], unique=False)
    op.create_table('emums_hr_flags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_character_id', sa.BigInteger(), nullable=False),
    sa.Column('target_character_name', sa.String(length=128), nullable=False),
    sa.Column('flag_key', sa.String(length=64), nullable=False),
    sa.Column('flag_label', sa.String(length=128), nullable=False),
    sa.Column('color', sa.String(length=24), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emums_hr_flags_flag_key'), 'emums_hr_flags', ['flag_key'], unique=False)
    op.create_index(op.f('ix_emums_hr_flags_target_character_id'), 'emums_hr_flags', ['target_character_id'], unique=False)
    op.create_table('emums_hr_leaves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_name', sa.String(length=128), nullable=False),
    sa.Column('character_id', sa.BigInteger(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emums_hr_leaves_status'), 'emums_hr_leaves', ['status'], unique=False)
    op.create_table('emums_industrial_build_structures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('structure_id', sa.BigInteger(), nullable=False),
    sa.Column('structure_name', sa.String(length=256), nullable=False),
    sa.Column('system_name', sa.String(length=128), nullable=False),
    sa.Column('location_label', sa.String(length=128), nullable=False),
    sa.Column('material_bonus_pct', sa.Float(), nullable=False),
    sa.Column('time_bonus_pct', sa.Float(), nullable=False),
    sa.Column('tax_pct', sa.Float(), nullable=False),
    sa.Column('has_manufacturing', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emums_industrial_build_structures_structure_id'), 'emums_industrial_build_structures', ['structure_id'], unique=True)
    op.create_table('emums_industrial_projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_code', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('container_name', sa.String(length=256), nullable=False),
    sa.Column('owner_character_name', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('material_cost_isk', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('job_cost_isk', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emums_industrial_projects_project_code'), 'emums_industrial_projects', ['project_code'], unique=True)
    op.create_index(op.f('ix_emums_industrial_projects_status'), 'emums_industrial_projects', ['status'], unique=False)
    op.create_table('emums_industry_calcs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('blueprint_type_id', sa.Integer(), nullable=False),
    sa.Column('blueprint_name', sa.String(length=128), nullable=False),
    sa.Column('runs', sa.Integer(), nullable=False),
    sa.Column('material_cost_isk', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('product_value_isk', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('profit_isk', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('emums_indy_blueprints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_character_name', sa.String(length=128), nullable=False),
    sa.Column('owner_scope', sa.String(length=16), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('type_name', sa.String(length=256), nullable=False),
    sa.Column('material_efficiency', sa.Integer(), nullable=False),
    sa.Column('time_efficiency', sa.Integer(), nullable=False),
    sa.Column('runs', sa.Integer(), nullable=False),
    sa.Column('location_name', sa.String(length=256), nullable=False),
    sa.Column('shared', sa.Boolean(), nullable=False),
    sa.Column('copy_available', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emums_indy_blueprints_type_id'), 'emums_indy_blueprints', ['type_id'], unique=False)
    op.create_table('emums_indy_copy_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requester', sa.String(length=128), nullable=False),
    sa.Column('blueprint_name', sa.String(length=256), nullable=False),
    sa.Column('runs', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('assignee', sa.String(length=128), nullable=False),
    sa.Column('delivery_location', sa.String(length=256), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emums_indy_copy_requests_status'), 'emums_indy_copy_requests', ['status'], unique=False)
    op.create_table('emums_indy_hub_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_type', sa.String(length=64), nullable=False),
    sa.Column('requester', sa.String(length=128), nullable=False),
    sa.Column('blueprint_name', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('runs', sa.Integer(), nullable=False),
    sa.Column('due_at', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emums_indy_hub_jobs_status'), 'emums_indy_hub_jobs', ['status'], unique=False)
    op.create_table('emums_indy_job_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_name', sa.String(length=128), nullable=False),
    sa.Column('blueprint_name', sa.String(length=256), nullable=False),
    sa.Column('activity', sa.String(length=32), nullable=False),
    sa.Column('runs', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('location_name', sa.String(length=256), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('output_type_name', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emums_indy_job_records_character_name'), 'emums_indy_job_records', ['character_name'], unique=False)
    op.create_index(op.f('ix_emums_indy_job_records_status'), 'emums_indy_job_records', ['status'], unique=False)
    op.create_table('emums_invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_number', sa.String(length=32), nullable=False),
    sa.Column('character_name', sa.String(length=128), nullable=False),
    sa.Column('corporation_name', sa.String(length=128), nullable=False),
    sa.Column('structure_name', sa.String(length=256), nullable=False),
    sa.Column('total_due_isk', sa.Numeric(), nullable=False),
    sa.Column('amount_paid_isk', sa.Numeric(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('due_at', sa.Date(), nullable=False),
    sa.Column('on_naughty_list', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emums_invoices_invoice_number'), 'emums_invoices', ['invoice_number'], unique=True)
    op.create_index(op.f('ix_emums_invoices_status'), 'emums_invoices', ['status'], unique=False)
    op.create_table('emums_killboard_leaderboard',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scope', sa.String(length=32), nullable=False),
    sa.Column('scope_id', sa.BigInteger(), nullable=False),
    sa.Column('period_days', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.BigInteger(), nullable=False),
    sa.Column('character_name', sa.String(length=128), nullable=False),
    sa.Column('kills', sa.Integer(), nullable=False),
    sa.Column('losses', sa.Integer(), nullable=False),
    sa.Column('isk_destroyed', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('isk_lost', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emums_killboard_leaderboard_character_id'), 'emums_killboard_leaderboard', ['character_id'], unique=False)
    op.create_index(op.f('ix_emums_killboard_leaderboard_scope_id'), 'emums_killboard_leaderboard', ['scope_id'], unique=False)
    op.create_table('emums_linked_characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_user_id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.BigInteger(), nullable=False),
    sa.Column('character_name', sa.String(length=128), nullable=False),
    sa.Column('corporation_id', sa.BigInteger(), nullable=False),
    sa.Column('is_main', sa.Boolean(), nullable=False),
    sa.Column('token_valid', sa.Boolean(), nullable=False),
    sa.Column('scopes_json', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emums_linked_characters_character_id'), 'emums_linked_characters', ['character_id'], unique=False)
    op.create_index(op.f('ix_emums_linked_characters_owner_user_id'), 'emums_linked_characters', ['owner_user_id'], unique=False)
    op.create_table('emums_market_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('average', sa.Float(), nullable=False),
    sa.Column('highest', sa.Float(), nullable=False),
    sa.Column('lowest', sa.Float(), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.Column('order_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emums_market_history_day'), 'emums_market_history', ['day'], unique=False)
    op.create_index(op.f('ix_emums_market_history_region_id'), 'emums_market_history', ['region_id'], unique=False)
    op.create_index(op.f('ix_emums_market_history_type_id'), 'emums_market_history', ['type_id'], unique=False)
    op.create_table('emums_market_watch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('type_name', sa.String(length=128), nullable=False),
    sa.Column('location_label', sa.String(length=128), nullable=False),
    sa.Column('best_buy', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('best_sell', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('spread_pct', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emums_market_watch_type_id'), 'emums_market_watch', ['type_id'], unique=False)
    op.create_table('emums_material_exchange_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_name', sa.String(length=128), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('type_name', sa.String(length=128), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price_isk', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emums_material_exchange_orders_status'), 'emums_material_exchange_orders', ['status'], unique=False)
    op.create_index(op.f('ix_emums_material_exchange_orders_type_id'), 'emums_material_exchange_orders', ['type_id'], unique=False)
    op.create_table('emums_message_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('subject', sa.String(length=256), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('variables_json', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emums_message_templates_slug'), 'emums_message_templates', ['slug'], unique=True)
    op.create_table('emums_mining_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mined_date', sa.Date(), nullable=False),
    sa.Column('structure_name', sa.String(length=256), nullable=False),
    sa.Column('character_id', sa.BigInteger(), nullable=False),
    sa.Column('character_name', sa.String(length=128), nullable=False),
    sa.Column('type_name', sa.String(length=128), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('moon_rarity', sa.String(length=8), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('isk_value', sa.Numeric(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emums_mining_logs_character_id'), 'emums_mining_logs', ['character_id'], unique=False)
    op.create_index(op.f('ix_emums_mining_logs_mined_date'), 'emums_mining_logs', ['mined_date'], unique=False)
    op.create_index(op.f('ix_emums_mining_logs_structure_name'), 'emums_mining_logs', ['structure_name'], unique=False)
    op.create_table('emums_notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plugin', sa.String(length=64), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emums_notifications_created_at'), 'emums_notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_emums_notifications_plugin'), 'emums_notifications', ['plugin'], unique=False)
    op.create_index(op.f('ix_emums_notifications_read'), 'emums_notifications', ['read'], unique=False)
    op.create_index(op.f('ix_emums_notifications_type'), 'emums_notifications', ['type'], unique=False)
    op.create_table('emums_org_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_name', sa.String(length=128), nullable=False),
    sa.Column('corporation_id', sa.BigInteger(), nullable=False),
    sa.Column('observer_corporation_id', sa.BigInteger(), nullable=False),
    sa.Column('tax_corp_name', sa.String(length=128), nullable=False),
    sa.Column('discord_webhook_url', sa.String(length=512), nullable=False),
    sa.Column('mail_enabled', sa.Boolean(), nullable=False),
    sa.Column('mail_sender_character', sa.String(length=128), nullable=False),
    sa.Column('propaganda_tagline', sa.String(length=256), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('emums_pni_bills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('statement_id', sa.Integer(), nullable=False),
    sa.Column('bill_type', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=False),
    sa.Column('amount_isk', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('due_at', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emums_pni_bills_statement_id'), 'emums_pni_bills', ['statement_id'], unique=False)
    op.create_table('emums_pni_statements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('period_label', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('total_income_isk', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('total_expense_isk', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('emums_project_job_costs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=False),
    sa.Column('activity', sa.String(length=32), nullable=False),
    sa.Column('runs', sa.Integer(), nullable=False),
    sa.Column('cost_isk', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('structure_name', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emums_project_job_costs_project_id'), 'emums_project_job_costs', ['project_id'], unique=False)
    op.create_table('emums_project_stock_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('type_name', sa.String(length=128), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_cost_isk', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('container_name', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emums_project_stock_assignments_project_id'), 'emums_project_stock_assignments', ['project_id'], unique=False)
    op.create_index(op.f('ix_emums_project_stock_assignments_type_id'), 'emums_project_stock_assignments', ['type_id'], unique=False)
    op.create_table('emums_ratting_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('period_id', sa.Integer(), nullable=False),
    sa.Column('character_name', sa.String(length=128), nullable=False),
    sa.Column('bounty_isk', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('tax_due_isk', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('paid_isk', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emums_ratting_payments_period_id'), 'emums_ratting_payments', ['period_id'], unique=False)
    op.create_table('emums_ratting_periods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('period_label', sa.String(length=64), nullable=False),
    sa.Column('rate_pct', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('total_bounty_isk', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('total_collected_isk', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('emums_rentable_moons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('structure_id', sa.BigInteger(), nullable=False),
    sa.Column('structure_name', sa.String(length=256), nullable=False),
    sa.Column('system_name', sa.String(length=128), nullable=False),
    sa.Column('moon_rarity', sa.String(length=8), nullable=False),
    sa.Column('monthly_rent_isk', sa.Numeric(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emums_rentable_moons_status'), 'emums_rentable_moons', ['status'], unique=False)
    op.create_index(op.f('ix_emums_rentable_moons_structure_id'), 'emums_rentable_moons', ['structure_id'], unique=True)
    op.create_index(op.f('ix_emums_rentable_moons_structure_name'), 'emums_rentable_moons', ['structure_name'], unique=False)
    op.create_table('emums_rental_acl',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.BigInteger(), nullable=True),
    sa.Column('corporation_id', sa.BigInteger(), nullable=True),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('notes', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emums_rental_acl_character_id'), 'emums_rental_acl', ['character_id'], unique=False)
    op.create_index(op.f('ix_emums_rental_acl_corporation_id'), 'emums_rental_acl', ['corporation_id'], unique=False)
    op.create_index(op.f('ix_emums_rental_acl_role'), 'emums_rental_acl', ['role'], unique=False)
    op.create_table('emums_rental_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('landlord_corporation_id', sa.BigInteger(), nullable=False),
    sa.Column('landlord_corporation_name', sa.String(length=128), nullable=False),
    sa.Column('wallet_division', sa.Integer(), nullable=False),
    sa.Column('payment_reference_prefix', sa.String(length=32), nullable=False),
    sa.Column('due_grace_days', sa.Integer(), nullable=False),
    sa.Column('reminder_days_json', sa.Text(), nullable=False),
    sa.Column('wallet_poll_character_id', sa.BigInteger(), nullable=True),
    sa.Column('auto_approve_applications', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('emums_route_bookmarks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('origin_system', sa.String(length=128), nullable=False),
    sa.Column('destination_system', sa.String(length=128), nullable=False),
    sa.Column('origin_system_id', sa.Integer(), nullable=True),
    sa.Column('destination_system_id', sa.Integer(), nullable=True),
    sa.Column('jumps', sa.Integer(), nullable=False),
    sa.Column('route_json', sa.Text(), nullable=False),
    sa.Column('security_max', sa.Float(), nullable=False),
    sa.Column('route_mode', sa.String(length=16), nullable=False),
    sa.Column('visibility', sa.String(length=16), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('waypoint_system_ids_json', sa.Text(), nullable=False),
    sa.Column('share_token', sa.String(length=32), nullable=True),
    sa.Column('owner_character_id', sa.BigInteger(), nullable=True),
    sa.Column('owner_character_name', sa.String(length=128), nullable=False),
    sa.Column('corporation_id', sa.BigInteger(), nullable=True),
    sa.Column('alliance_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emums_route_bookmarks_share_token'), 'emums_route_bookmarks', ['share_token'], unique=True)
    op.create_table('emums_sde_stargates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_system_id', sa.Integer(), nullable=False),
    sa.Column('to_system_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emums_sde_stargates_from_system_id'), 'emums_sde_stargates', ['from_system_id'], unique=False)
    op.create_index(op.f('ix_emums_sde_stargates_to_system_id'), 'emums_sde_stargates', ['to_system_id'], unique=False)
    op.create_table('emums_sde_system_activity_hours',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('system_id', sa.Integer(), nullable=False),
    sa.Column('hour_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ship_jumps', sa.Integer(), nullable=False),
    sa.Column('ship_kills', sa.Integer(), nullable=False),
    sa.Column('pod_kills', sa.Integer(), nullable=False),
    sa.Column('npc_kills', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emums_sde_system_activity_hours_hour_ts'), 'emums_sde_system_activity_hours', ['hour_ts'], unique=False)
    op.create_index(op.f('ix_emums_sde_system_activity_hours_system_id'), 'emums_sde_system_activity_hours', ['system_id'], unique=False)
    op.create_table('emums_sde_systems',
    sa.Column('system_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('security', sa.Float(), nullable=False),
    sa.Column('region_name', sa.String(length=128), nullable=False),
    sa.Column('constellation_name', sa.String(length=128), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=True),
    sa.Column('constellation_id', sa.Integer(), nullable=True),
    sa.Column('x', sa.Float(), nullable=True),
    sa.Column('y', sa.Float(), nullable=True),
    sa.Column('z', sa.Float(), nullable=True),
    sa.Column('layout_x', sa.Float(), nullable=True),
    sa.Column('layout_y', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('system_id')
    )
    op.create_index(op.f('ix_emums_sde_systems_name'), 'emums_sde_systems', ['name'], unique=False)
    op.create_table('emums_sde_types',
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('group_name', sa.String(length=128), nullable=False),
    sa.Column('category_name', sa.String(length=128), nullable=False),
    sa.Column('volume_m3', sa.Float(), nullable=False),
    sa.Column('base_price', sa.Numeric(precision=16, scale=4), nullable=False),
    sa.PrimaryKeyConstraint('type_id')
    )
    op.create_index(op.f('ix_emums_sde_types_name'), 'emums_sde_types', ['name'], unique=False)
    op.create_table('emums_service_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service', sa.String(length=32), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=False),
    sa.Column('requires_sso', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emums_service_links_service'), 'emums_service_links', ['service'], unique=False)
    op.create_table('emums_srp_losses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('killmail_id', sa.BigInteger(), nullable=False),
    sa.Column('character_id', sa.BigInteger(), nullable=False),
    sa.Column('character_name', sa.String(length=128), nullable=False),
    sa.Column('ship_type_name', sa.String(length=128), nullable=False),
    sa.Column('total_value_isk', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('srp_amount_isk', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('zkill_url', sa.String(length=256), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emums_srp_losses_character_id'), 'emums_srp_losses', ['character_id'], unique=False)
    op.create_index(op.f('ix_emums_srp_losses_killmail_id'), 'emums_srp_losses', ['killmail_id'], unique=True)
    op.create_index(op.f('ix_emums_srp_losses_status'), 'emums_srp_losses', ['status'], unique=False)
    op.create_table('emums_sso_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.BigInteger(), nullable=False),
    sa.Column('character_name', sa.String(length=128), nullable=False),
    sa.Column('corporation_id', sa.BigInteger(), nullable=False),
    sa.Column('corporation_name', sa.String(length=128), nullable=False),
    sa.Column('alliance_id', sa.BigInteger(), nullable=True),
    sa.Column('alliance_name', sa.String(length=128), nullable=False),
    sa.Column('access_token_enc', sa.Text(), nullable=False),
    sa.Column('refresh_token_enc', sa.Text(), nullable=False),
    sa.Column('scopes_json', sa.Text(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emums_sso_users_character_id'), 'emums_sso_users', ['character_id'], unique=True)
    op.create_table('emums_storefront_listings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seller_character_name', sa.String(length=128), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('type_name', sa.String(length=128), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('suggested_price_isk', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('price_public_isk', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('price_corp_isk', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('price_alliance_isk', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('pricing_mode', sa.String(length=24), nullable=False),
    sa.Column('visibility', sa.String(length=24), nullable=False),
    sa.Column('price_basis', sa.String(length=64), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emums_storefront_listings_type_id'), 'emums_storefront_listings', ['type_id'], unique=False)
    op.create_table('emums_structure_tax_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pattern', sa.String(length=256), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('r16_pct', sa.Numeric(), nullable=False),
    sa.Column('r32_pct', sa.Numeric(), nullable=False),
    sa.Column('r64_pct', sa.Numeric(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.String(length=512), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('emums_rental_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('moon_id', sa.Integer(), nullable=False),
    sa.Column('applicant_character_id', sa.BigInteger(), nullable=False),
    sa.Column('applicant_character_name', sa.String(length=128), nullable=False),
    sa.Column('renter_corporation_id', sa.BigInteger(), nullable=False),
    sa.Column('renter_corporation_name', sa.String(length=128), nullable=False),
    sa.Column('monthly_rent_offered_isk', sa.Numeric(), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('reviewed_by_character_id', sa.BigInteger(), nullable=True),
    sa.Column('reviewed_by_character_name', sa.String(length=128), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['moon_id'], ['emums_rentable_moons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emums_rental_applications_applicant_character_id'), 'emums_rental_applications', ['applicant_character_id'], unique=False)
    op.create_index(op.f('ix_emums_rental_applications_created_at'), 'emums_rental_applications', ['created_at'], unique=False)
    op.create_index(op.f('ix_emums_rental_applications_moon_id'), 'emums_rental_applications', ['moon_id'], unique=False)
    op.create_index(op.f('ix_emums_rental_applications_renter_corporation_id'), 'emums_rental_applications', ['renter_corporation_id'], unique=False)
    op.create_index(op.f('ix_emums_rental_applications_status'), 'emums_rental_applications', ['status'], unique=False)
    op.create_table('emums_moon_leases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('moon_id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=True),
    sa.Column('renter_corporation_id', sa.BigInteger(), nullable=False),
    sa.Column('renter_corporation_name', sa.String(length=128), nullable=False),
    sa.Column('contact_character_id', sa.BigInteger(), nullable=True),
    sa.Column('contact_character_name', sa.String(length=128), nullable=False),
    sa.Column('started_at', sa.Date(), nullable=False),
    sa.Column('ends_at', sa.Date(), nullable=True),
    sa.Column('monthly_rent_isk', sa.Numeric(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['emums_rental_applications.id'], ),
    sa.ForeignKeyConstraint(['moon_id'], ['emums_rentable_moons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emums_moon_leases_moon_id'), 'emums_moon_leases', ['moon_id'], unique=False)
    op.create_index(op.f('ix_emums_moon_leases_renter_corporation_id'), 'emums_moon_leases', ['renter_corporation_id'], unique=False)
    op.create_index(op.f('ix_emums_moon_leases_status'), 'emums_moon_leases', ['status'], unique=False)
    op.create_table('emums_rental_bills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lease_id', sa.Integer(), nullable=False),
    sa.Column('bill_number', sa.String(length=32), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('amount_due_isk', sa.Numeric(), nullable=False),
    sa.Column('amount_paid_isk', sa.Numeric(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('due_at', sa.Date(), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('wallet_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('reminders_sent_json', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lease_id'], ['emums_moon_leases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emums_rental_bills_bill_number'), 'emums_rental_bills', ['bill_number'], unique=True)
    op.create_index(op.f('ix_emums_rental_bills_due_at'), 'emums_rental_bills', ['due_at'], unique=False)
    op.create_index(op.f('ix_emums_rental_bills_lease_id'), 'emums_rental_bills', ['lease_id'], unique=False)
    op.create_index(op.f('ix_emums_rental_bills_status'), 'emums_rental_bills', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_emums_rental_bills_status'), table_name='emums_rental_bills')
    op.drop_index(op.f('ix_emums_rental_bills_lease_id'), table_name='emums_rental_bills')
    op.drop_index(op.f('ix_emums_rental_bills_due_at'), table_name='emums_rental_bills')
    op.drop_index(op.f('ix_emums_rental_bills_bill_number'), table_name='emums_rental_bills')
    op.drop_table('emums_rental_bills')
    op.drop_index(op.f('ix_emums_moon_leases_status'), table_name='emums_moon_leases')
    op.drop_index(op.f('ix_emums_moon_leases_renter_corporation_id'), table_name='emums_moon_leases')
    op.drop_index(op.f('ix_emums_moon_leases_moon_id'), table_name='emums_moon_leases')
    op.drop_table('emums_moon_leases')
    op.drop_index(op.f('ix_emums_rental_applications_status'), table_name='emums_rental_applications')
    op.drop_index(op.f('ix_emums_rental_applications_renter_corporation_id'), table_name='emums_rental_applications')
    op.drop_index(op.f('ix_emums_rental_applications_moon_id'), table_name='emums_rental_applications')
    op.drop_index(op.f('ix_emums_rental_applications_created_at'), table_name='emums_rental_applications')
    op.drop_index(op.f('ix_emums_rental_applications_applicant_character_id'), table_name='emums_rental_applications')
    op.drop_table('emums_rental_applications')
    op.drop_table('emums_structure_tax_rules')
    op.drop_index(op.f('ix_emums_storefront_listings_type_id'), table_name='emums_storefront_listings')
    op.drop_table('emums_storefront_listings')
    op.drop_index(op.f('ix_emums_sso_users_character_id'), table_name='emums_sso_users')
    op.drop_table('emums_sso_users')
    op.drop_index(op.f('ix_emums_srp_losses_status'), table_name='emums_srp_losses')
    op.drop_index(op.f('ix_emums_srp_losses_killmail_id'), table_name='emums_srp_losses')
    op.drop_index(op.f('ix_emums_srp_losses_character_id'), table_name='emums_srp_losses')
    op.drop_table('emums_srp_losses')
    op.drop_index(op.f('ix_emums_service_links_service'), table_name='emums_service_links')
    op.drop_table('emums_service_links')
    op.drop_index(op.f('ix_emums_sde_types_name'), table_name='emums_sde_types')
    op.drop_table('emums_sde_types')
    op.drop_index(op.f('ix_emums_sde_systems_name'), table_name='emums_sde_systems')
    op.drop_table('emums_sde_systems')
    op.drop_index(op.f('ix_emums_sde_system_activity_hours_system_id'), table_name='emums_sde_system_activity_hours')
    op.drop_index(op.f('ix_emums_sde_system_activity_hours_hour_ts'), table_name='emums_sde_system_activity_hours')
    op.drop_table('emums_sde_system_activity_hours')
    op.drop_index(op.f('ix_emums_sde_stargates_to_system_id'), table_name='emums_sde_stargates')
    op.drop_index(op.f('ix_emums_sde_stargates_from_system_id'), table_name='emums_sde_stargates')
    op.drop_table('emums_sde_stargates')
    op.drop_index(op.f('ix_emums_route_bookmarks_share_token'), table_name='emums_route_bookmarks')
    op.drop_table('emums_route_bookmarks')
    op.drop_table('emums_rental_settings')
    op.drop_index(op.f('ix_emums_rental_acl_role'), table_name='emums_rental_acl')
    op.drop_index(op.f('ix_emums_rental_acl_corporation_id'), table_name='emums_rental_acl')
    op.drop_index(op.f('ix_emums_rental_acl_character_id'), table_name='emums_rental_acl')
    op.drop_table('emums_rental_acl')
    op.drop_index(op.f('ix_emums_rentable_moons_structure_name'), table_name='emums_rentable_moons')
    op.drop_index(op.f('ix_emums_rentable_moons_structure_id'), table_name='emums_rentable_moons')
    op.drop_index(op.f('ix_emums_rentable_moons_status'), table_name='emums_rentable_moons')
    op.drop_table('emums_rentable_moons')
    op.drop_table('emums_ratting_periods')
    op.drop_index(op.f('ix_emums_ratting_payments_period_id'), table_name='emums_ratting_payments')
    op.drop_table('emums_ratting_payments')
    op.drop_index(op.f('ix_emums_project_stock_assignments_type_id'), table_name='emums_project_stock_assignments')
    op.drop_index(op.f('ix_emums_project_stock_assignments_project_id'), table_name='emums_project_stock_assignments')
    op.drop_table('emums_project_stock_assignments')
    op.drop_index(op.f('ix_emums_project_job_costs_project_id'), table_name='emums_project_job_costs')
    op.drop_table('emums_project_job_costs')
    op.drop_table('emums_pni_statements')
    op.drop_index(op.f('ix_emums_pni_bills_statement_id'), table_name='emums_pni_bills')
    op.drop_table('emums_pni_bills')
    op.drop_table('emums_org_settings')
    op.drop_index(op.f('ix_emums_notifications_type'), table_name='emums_notifications')
    op.drop_index(op.f('ix_emums_notifications_read'), table_name='emums_notifications')
    op.drop_index(op.f('ix_emums_notifications_plugin'), table_name='emums_notifications')
    op.drop_index(op.f('ix_emums_notifications_created_at'), table_name='emums_notifications')
    op.drop_table('emums_notifications')
    op.drop_index(op.f('ix_emums_mining_logs_structure_name'), table_name='emums_mining_logs')
    op.drop_index(op.f('ix_emums_mining_logs_mined_date'), table_name='emums_mining_logs')
    op.drop_index(op.f('ix_emums_mining_logs_character_id'), table_name='emums_mining_logs')
    op.drop_table('emums_mining_logs')
    op.drop_index(op.f('ix_emums_message_templates_slug'), table_name='emums_message_templates')
    op.drop_table('emums_message_templates')
    op.drop_index(op.f('ix_emums_material_exchange_orders_type_id'), table_name='emums_material_exchange_orders')
    op.drop_index(op.f('ix_emums_material_exchange_orders_status'), table_name='emums_material_exchange_orders')
    op.drop_table('emums_material_exchange_orders')
    op.drop_index(op.f('ix_emums_market_watch_type_id'), table_name='emums_market_watch')
    op.drop_table('emums_market_watch')
    op.drop_index(op.f('ix_emums_market_history_type_id'), table_name='emums_market_history')
    op.drop_index(op.f('ix_emums_market_history_region_id'), table_name='emums_market_history')
    op.drop_index(op.f('ix_emums_market_history_day'), table_name='emums_market_history')
    op.drop_table('emums_market_history')
    op.drop_index(op.f('ix_emums_linked_characters_owner_user_id'), table_name='emums_linked_characters')
    op.drop_index(op.f('ix_emums_linked_characters_character_id'), table_name='emums_linked_characters')
    op.drop_table('emums_linked_characters')
    op.drop_index(op.f('ix_emums_killboard_leaderboard_scope_id'), table_name='emums_killboard_leaderboard')
    op.drop_index(op.f('ix_emums_killboard_leaderboard_character_id'), table_name='emums_killboard_leaderboard')
    op.drop_table('emums_killboard_leaderboard')
    op.drop_index(op.f('ix_emums_invoices_status'), table_name='emums_invoices')
    op.drop_index(op.f('ix_emums_invoices_invoice_number'), table_name='emums_invoices')
    op.drop_table('emums_invoices')
    op.drop_index(op.f('ix_emums_indy_job_records_status'), table_name='emums_indy_job_records')
    op.drop_index(op.f('ix_emums_indy_job_records_character_name'), table_name='emums_indy_job_records')
    op.drop_table('emums_indy_job_records')
    op.drop_index(op.f('ix_emums_indy_hub_jobs_status'), table_name='emums_indy_hub_jobs')
    op.drop_table('emums_indy_hub_jobs')
    op.drop_index(op.f('ix_emums_indy_copy_requests_status'), table_name='emums_indy_copy_requests')
    op.drop_table('emums_indy_copy_requests')
    op.drop_index(op.f('ix_emums_indy_blueprints_type_id'), table_name='emums_indy_blueprints')
    op.drop_table('emums_indy_blueprints')
    op.drop_table('emums_industry_calcs')
    op.drop_index(op.f('ix_emums_industrial_projects_status'), table_name='emums_industrial_projects')
    op.drop_index(op.f('ix_emums_industrial_projects_project_code'), table_name='emums_industrial_projects')
    op.drop_table('emums_industrial_projects')
    op.drop_index(op.f('ix_emums_industrial_build_structures_structure_id'), table_name='emums_industrial_build_structures')
    op.drop_table('emums_industrial_build_structures')
    op.drop_index(op.f('ix_emums_hr_leaves_status'), table_name='emums_hr_leaves')
    op.drop_table('emums_hr_leaves')
    op.drop_index(op.f('ix_emums_hr_flags_target_character_id'), table_name='emums_hr_flags')
    op.drop_index(op.f('ix_emums_hr_flags_flag_key'), table_name='emums_hr_flags')
    op.drop_table('emums_hr_flags')
    op.drop_index(op.f('ix_emums_hr_blacklist_character_name'), table_name='emums_hr_blacklist')
    op.drop_table('emums_hr_blacklist')
    op.drop_index(op.f('ix_emums_fittings_doctrine_slug'), table_name='emums_fittings')
    op.drop_table('emums_fittings')
    op.drop_table('emums_desktop_backgrounds')
    op.drop_index(op.f('ix_emums_dashboard_snapshots_metric_key'), table_name='emums_dashboard_snapshots')
    op.drop_table('emums_dashboard_snapshots')
    op.drop_index(op.f('ix_emums_corp_market_orders_type_id'), table_name='emums_corp_market_orders')
    op.drop_index(op.f('ix_emums_corp_market_orders_status'), table_name='emums_corp_market_orders')
    op.drop_index(op.f('ix_emums_corp_market_orders_buyer_character_id'), table_name='emums_corp_market_orders')
    op.drop_table('emums_corp_market_orders')
    op.drop_index(op.f('ix_emums_corp_market_listings_type_id'), table_name='emums_corp_market_listings')
    op.drop_index(op.f('ix_emums_corp_market_listings_status'), table_name='emums_corp_market_listings')
    op.drop_table('emums_corp_market_listings')
    op.drop_index(op.f('ix_emums_character_skill_levels_skill_type_id'), table_name='emums_character_skill_levels')
    op.drop_index(op.f('ix_emums_character_skill_levels_character_id'), table_name='emums_character_skill_levels')
    op.drop_table('emums_character_skill_levels')
    op.drop_index(op.f('ix_emums_buyback_quotes_share_token'), table_name='emums_buyback_quotes')
    op.drop_index(op.f('ix_emums_buyback_quotes_created_at'), table_name='emums_buyback_quotes')
    op.drop_table('emums_buyback_quotes')
    op.drop_index(op.f('ix_emums_blueprint_public_contracts_contract_id'), table_name='emums_blueprint_public_contracts')
    op.drop_table('emums_blueprint_public_contracts')
    op.drop_index(op.f('ix_emums_authed_structures_structure_id'), table_name='emums_authed_structures')
    op.drop_table('emums_authed_structures')
    op.drop_index(op.f('ix_emums_audit_profiles_character_id'), table_name='emums_audit_profiles')
    op.drop_table('emums_audit_profiles')
    op.drop_index(op.f('ix_emums_appraisal_reports_share_token'), table_name='emums_appraisal_reports')
    op.drop_index(op.f('ix_emums_appraisal_reports_created_at'), table_name='emums_appraisal_reports')
    op.drop_table('emums_appraisal_reports')
    # ### end Alembic commands ###
